# Generated by Django 5.0.6 on 2024-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('display_fields', models.TextField(default='')),
                ('filter_fields', models.TextField(default='')),
                ('geometry_field', models.TextField(blank=True, default=None, null=True)),
                ('datetime_field', models.TextField(blank=True, default=None, null=True)),
                ('geometry_filter_field', models.TextField(blank=True, default=None, null=True)),
                ('locations_field', models.TextField(blank=True, default=None, null=True)),
                ('z_field', models.TextField(blank=True, default=None, null=True)),
                ('api_type', models.CharField(choices=[('FEATURES', 'Features'), ('EDR', 'EDR')], default='FEATURES', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'collections',
            },
        ),
        migrations.CreateModel(
            name='GeoAPIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default='http://localhost:8000/api/', max_length=400, verbose_name='Base GeoAPI URL')),
                ('max_table_name_length', models.SmallIntegerField(default=30)),
                ('output_dir', models.CharField(default='/results', max_length=400, verbose_name='GeoAPI Output Directory path')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('successful', 'successful'), ('accepted', 'accepted'), ('running', 'running'), ('failed', 'failed'), ('dismissed', 'dismissed')], default='accepted', max_length=10)),
                ('progress', models.SmallIntegerField(default=0)),
                ('created_datetime', models.DateTimeField(default=None, null=True)),
                ('start_datetime', models.DateTimeField(default=None, null=True)),
                ('end_datetime', models.DateTimeField(default=None, null=True)),
                ('updated_datetime', models.DateTimeField(default=None, null=True)),
                ('process_id', models.CharField(max_length=50)),
                ('type', models.CharField(default='process', max_length=10)),
                ('execution_type', models.CharField(choices=[('SYNC', 'sync'), ('ASYNC', 'async')], default=None, max_length=10, null=True)),
                ('message', models.TextField(default='')),
                ('duration', models.FloatField(default=None, null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
