# Generated by Django 5.0.1 on 2024-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0005_rename_utm_nort_airqualitysensor_utm_north'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitysensor',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
