# Generated by Django 5.0.1 on 2024-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0009_rename_airqualitymeasure_airqualitymeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='api_type',
            field=models.CharField(choices=[('FEATURES', 'Features'), ('EDR', 'EDR')], default='FEATURES', max_length=8),
        ),
    ]
