# Generated by Django 5.0.1 on 2024-01-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0010_collections_api_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitymeasurement',
            name='sensor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoapi.airqualitysensor'),
        ),
    ]
