# Generated by Django 5.0.1 on 2024-01-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0011_alter_airqualitymeasurement_sensor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airqualitymeasurement',
            options={'verbose_name_plural': 'Air Quality Measurements'},
        ),
        migrations.AlterModelOptions(
            name='airqualitysensor',
            options={'verbose_name_plural': 'Air Quality Sensors'},
        ),
        migrations.AddConstraint(
            model_name='airqualitymeasurement',
            constraint=models.UniqueConstraint(models.F('sensor_id'), models.F('date'), models.F('value'), name='unique_data'),
        ),
    ]
