# Generated by Django 5.0.1 on 2024-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0012_alter_airqualitymeasurement_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='airqualitymeasurement',
            name='unique_data',
        ),
        migrations.AddField(
            model_name='collections',
            name='locations_field',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
