# Generated by Django 5.0.1 on 2024-02-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0022_alter_meteomeasurement_sensor_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
