# Generated by Django 5.0.1 on 2024-02-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0025_alter_collection_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAPIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=400, verbose_name='Base GeoAPI URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='meteomeasurement',
            name='sensor_id',
        ),
        migrations.DeleteModel(
            name='AirQualityMeasurement',
        ),
        migrations.DeleteModel(
            name='AirQualitySensor',
        ),
        migrations.DeleteModel(
            name='MeteoMeasurement',
        ),
        migrations.DeleteModel(
            name='MeteoSensor',
        ),
    ]
