# Generated by Django 5.0.1 on 2024-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0026_geoapiconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='z_field',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
