# Generated by Django 5.0.1 on 2024-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0026_geoapiconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('COMPLETED', 'completed'), ('RUNNING', 'running'), ('FAILED', 'failed'), ('DISMISSED', 'dismissed')], default='RUNNING', max_length=9)),
                ('progress', models.IntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('process_id', models.CharField()),
                ('result', models.CharField()),
            ],
        ),
    ]
