# Generated by Django 5.0.1 on 2024-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0027_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='process_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.CharField(max_length=200),
        ),
    ]
