# Generated by Django 5.0.1 on 2024-04-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0027_collection_z_field'),
        ('geoapi', '0031_job_type'),
    ]

    operations = [
    ]
