# Generated by Django 5.0.1 on 2024-04-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0032_merge_0027_collection_z_field_0031_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoapiconfiguration',
            name='max_table_name_length',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='geoapiconfiguration',
            name='output_dir',
            field=models.CharField(default='/tmp/roseapi', max_length=400, verbose_name='GeoAPI Output Directory path'),
        ),
        migrations.AlterField(
            model_name='geoapiconfiguration',
            name='base_url',
            field=models.CharField(default='http://localhost:8000/api/', max_length=400, verbose_name='Base GeoAPI URL'),
        ),
    ]
