# Generated by Django 5.0.6 on 2024-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0033_geoapiconfiguration_max_table_name_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='geoapiconfiguration',
            name='output_dir',
            field=models.CharField(default='/results', max_length=400, verbose_name='GeoAPI Output Directory path'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
