# Generated by Django 5.0.6 on 2024-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0034_job_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='execution_type',
            field=models.CharField(choices=[('SUCCESSFUL', 'successful'), ('ACCEPTED', 'accepted'), ('RUNNING', 'running'), ('FAILED', 'failed'), ('DISMISSED', 'dismissed')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(default='process', max_length=10),
        ),
    ]
