# Generated by Django 5.0.6 on 2024-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0035_job_execution_type_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='execution_type',
            field=models.CharField(choices=[('SYNC', 'sync'), ('ASYNC', 'async')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('successful', 'successful'), ('accepted', 'accepted'), ('running', 'running'), ('failed', 'failed'), ('dismissed', 'dismissed')], default='accepted', max_length=10),
        ),
    ]
