# Generated by Django 5.0.6 on 2024-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0036_alter_job_execution_type_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.FloatField(default=None, null=True),
        ),
    ]
