# Generated by Django 5.0.6 on 2024-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0037_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
