# Generated by Django 5.0.1 on 2024-01-29 13:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityStation',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sensor_type', models.CharField(max_length=30)),
                ('measurement_unit', models.CharField(max_length=5)),
                ('station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=60)),
                ('altitude', models.IntegerField()),
                ('province', models.CharField(max_length=2)),
                ('comune', models.CharField(max_length=30)),
                ('is_historical', models.BooleanField()),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('utm_nort', models.DecimalField(decimal_places=4, max_digits=11)),
                ('utm_east', models.DecimalField(decimal_places=4, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapi.airqualitystation')),
            ],
        ),
    ]
