# Generated by Django 5.0.1 on 2024-01-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirQualityStation',
            new_name='AirQualitySensor',
        ),
    ]
