# Generated by Django 5.0.1 on 2024-01-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0004_alter_collections_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualitysensor',
            old_name='utm_nort',
            new_name='utm_north',
        ),
    ]
