# Generated by Django 5.0.1 on 2024-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0006_alter_airqualitysensor_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitysensor',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
    ]
