# Generated by Django 5.0.1 on 2024-01-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0007_alter_airqualitysensor_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitymeasure',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
