# Generated by Django 5.0.1 on 2024-01-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0008_alter_airqualitymeasure_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirQualityMeasure',
            new_name='AirQualityMeasurement',
        ),
    ]
