# Generated by Django 5.0.1 on 2024-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0014_collections_datetime_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='locations_field',
        ),
        migrations.AlterField(
            model_name='collections',
            name='datetime_field',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='geometry_field',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='geometry_filter_field',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
