# Generated by Django 5.0.1 on 2024-02-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0015_remove_collections_locations_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='geometry_field',
        ),
    ]
