# Generated by Django 5.0.1 on 2024-02-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0017_collections_geometry_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='locations_field',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
