# Generated by Django 5.0.1 on 2024-02-09 12:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoapi", "0018_collections_locations_field"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MeteoMeasure",
            new_name="MeteoMeasurement",
        ),
        migrations.AlterModelOptions(
            name="meteosensor",
            options={"verbose_name_plural": "Meteo Sensors"},
        ),
        migrations.RemoveField(
            model_name="meteosensor",
            name="id",
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="altitude",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="date_start",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="date_stop",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="is_historical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="latitude",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="longitude",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="measurement_unit",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="province",
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="sensor_id",
            field=models.IntegerField(
                default=None, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="sensor_type",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="station_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="station_name",
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="utm_east",
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteosensor",
            name="utm_north",
            field=models.DecimalField(decimal_places=4, default=None, max_digits=11),
            preserve_default=False,
        ),
    ]
