# Generated by Django 5.0.1 on 2024-02-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoapi", "0019_rename_meteomeasure_meteomeasurement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meteomeasurement",
            options={"verbose_name_plural": "Air Quality Measurements"},
        ),
        migrations.AddField(
            model_name="meteomeasurement",
            name="date",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteomeasurement",
            name="operative_id",
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteomeasurement",
            name="sensor_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geoapi.airqualitysensor",
            ),
        ),
        migrations.AddField(
            model_name="meteomeasurement",
            name="status",
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meteomeasurement",
            name="value",
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
