# Generated by Django 5.0.1 on 2024-02-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoapi", "0021_alter_meteomeasurement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meteomeasurement",
            name="sensor_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geoapi.meteosensor",
            ),
        ),
    ]
