# Generated by Django 5.0.1 on 2024-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0023_rename_collections_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='fields',
            field=models.JSONField(default=dict),
        ),
    ]
