# Generated by Django 5.0.1 on 2024-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0024_collection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='fields',
            field=models.JSONField(default=list),
        ),
    ]
