# Generated by Django 5.0.1 on 2024-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0029_alter_job_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('SUCCESSFUL', 'successful'), ('ACCEPTED', 'accepted'), ('RUNNING', 'running'), ('FAILED', 'failed'), ('DISMISSED', 'dismissed')], default='ACCEPTED', max_length=10),
        ),
    ]
