# Generated by Django 5.0.1 on 2024-04-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0030_job_created_datetime_alter_job_start_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('SUCCESSFUL', 'successful'), ('ACCEPTED', 'accepted'), ('RUNNING', 'running'), ('FAILED', 'failed'), ('DISMISSED', 'dismissed')], default=None, max_length=10, null=True),
        ),
    ]
